[tool.poetry]
name = "gislearn"
version = "0.1.0"
description = ""
authors = ["Christopher Scott <cscott9251@virginmedia.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
